### ISSUE TITLE
分页组件默认是英文，设置中文不生效

### ISSUE THREAD

**Issue by Lelouch-zero** [xiaoxian521/pure-admin-table#3]
![image](https://user-images.githubusercontent.com/13629629/181177303-b3f6abc2-354f-4b26-96a1-f4bacc336337.png)

**Comment by xiaoxian521** [comment]
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/44761321/181181266-c984edba-e547-44c6-a8d2-c8658b49e3c8.png">

**Comment by xiaoxian521** [comment]
https://vue-pure-admin-git-refactor-themes-xiaoxian521.vercel.app/#/system/user/index
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/44761321/181181708-21a09db5-25cf-4c77-a531-65d43aeaf747.png">

**Comment by uino-wuixn** [comment]
我也是设置不了中文，好伤啊
![Uploading image.png…]()

**Comment by uino-wuixn** [comment]
![image](https://user-images.githubusercontent.com/73518894/221350137-c49c5772-08b1-4dab-8562-9b917efca92c.png)

**Comment by uino-wuixn** [comment]
我也是设置不了中文，好伤啊
![Uploading image.png…]()
