### ISSUE TITLE
组件没有渲染，原因是什么

### ISSUE THREAD

**Issue by fs821031547** [xiaoxian521/pure-admin-table#4]
![image](https://user-images.githubusercontent.com/15795249/184114613-16c14f37-7313-4d00-9092-30c2ac602b8b.png)

**Comment by fs821031547** [comment]
![image](https://user-images.githubusercontent.com/15795249/184116968-5ec5105f-607e-494e-a0b5-0e098c7cd8c2.png)
![image](https://user-images.githubusercontent.com/15795249/184117008-21c18502-5c74-40b7-8a30-8d7867514583.png)
组件通过main全局引入

**Comment by xiaoxian521** [comment]
全局安装element-plus获取把你用到的element-plus的组件都引人

**Comment by xiaoxian521** [comment]
参考例子

**Comment by fs821031547** [comment]
> 全局安装element-plus获取把你用到的element-plus的组件都引人

我是按照官方推荐的自动导入组件的方式使用的，不支持吗？

**Comment by xiaoxian521** [comment]
可以提供简单的复现仓库 有空我会看

**Comment by xiaoxian521** [comment]
参考：https://github.com/xiaoxian521/pure-admin-table/tree/main/playgrounds/auto-import-demo
