### ISSUE TITLE
建议: 希望可以将分页组件与表格组件分出来

### ISSUE THREAD

**Issue by Canroc** [xiaoxian521/pure-admin-table#5]
当前版本分页栏在进行变动时 会出现表格与分页组件一起重新渲染，对用户体验不是太好 有点晃眼的感觉。
我觉得可以在puretable组件内部中分出table组件与page组件架构应该会好

**Comment by xiaoxian521** [comment]
我很好奇 分页变动表格不是应该就变动吗

**Comment by xiaoxian521** [comment]
抽出来干啥？？？？分页组件又不难 抽出来没有任何意义

**Comment by Canroc** [comment]
我的意思是表格重新渲染 分页组件就不要重新渲染了

**Comment by xiaoxian521** [comment]
那很好版啊 你不传分页参数啊 自己写分页

**Comment by xiaoxian521** [comment]
此种情况可通过 `loading` 处理，不需要用户再外部定义 `loading` 了，下个版本发布，支持 `loading` 参数

**Comment by xiaoxian521** [comment]
已处理
演示：https://xiaoxian521.github.io/pure-admin-table/
代码参考：https://github.com/xiaoxian521/pure-admin-table/blob/main/src/App.vue#L35-L36
