### ISSUE TITLE
单选示例中，选中一行后，钩子 `current-change` 没有调用

### ISSUE THREAD

**Issue by mou-xiangbo** [xiaoxian521/pure-admin-table#8]
可能和分页中当前页改变钩子的函数名相同，被覆盖了。
![image](https://user-images.githubusercontent.com/83263087/210193603-63e4c6d3-4623-4d24-8bd3-cb7041e44726.png)
![image](https://user-images.githubusercontent.com/83263087/210193667-45c72e51-4070-4811-bf14-3c3dd336ae20.png)

**Comment by xiaoxian521** [comment]
[fixed](https://github.com/xiaoxian521/pure-admin-table/releases/tag/v2.0.0)
